### ISSUE TITLE
Removal

### ISSUE THREAD

**Issue by phonkv2** [Viceroyy/AmalgamEdits#1]
Is it possible to remove the Hp and HP+ from the cheat as its useless and just have overheal![image](https://github.com/user-attachments/assets/ce995746-a09b-4c17-979b-81fd64c66e5f)

**Comment by Viceroyy** [comment]
Sure I can get rid of HP and combine them to one HP+

**Comment by phonkv2** [comment]
> Sure I can get rid of HP and combine them to one HP+

alright thanks
